import type { Metadata } from "next";
import { Inter, Poppins, Oxanium, Montserrat } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "./_components/header";

const oxanium = Oxanium({
  subsets: ["latin"],
  weight: ["200", "500", "600", "700"],
});
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400","500" ,"600", "700"],
});
const inter = Inter({
  subsets: ["latin"],
});
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "600"],
});
export const metadata: Metadata = {
  title: "Oss-Serviços",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          `w-full bg-gray-950 font-sans antialiased ${poppins.className} ${inter.className} ${oxanium.className} ${montserrat.className}`
        )}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
